name: spender
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  intl: ^0.15.8
  share: ^0.6.4+3
  month_picker_strip: ^0.0.3
  charts_flutter: ^0.8.1
  date_util: ^0.1.4
  shared_preferences:
  path_provider:
  simple_autocomplete_formfield: ^0.2.7
  autocomplete_textfield: ^1.7.3
  sqflite:  ^0.11.0+1
  string_validator: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  ios: true
  android: true
  image_path_ios: "asset/icon/appIcon.png"
  image_path_android: "asset/icon/appIcon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/home_clipart.png
    - images/rupee.png
    - images/Splashscren_withlogo.png
    - images/logo_alone.png
    - images/borrow.png
    - images/lend.png
    - images/no_results_found.png
    - images/rupee_purple.png
    - images/ribbon.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: asset/fonts/Poppins-Italic.ttf
        - asset: asset/fonts/Poppins-Medium.ttf
        - asset: asset/fonts/Poppins-Regular.ttf
        - asset: asset/fonts/Poppins-SemiBold.ttf
        - asset: asset/fonts/Poppins-Thin.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: asset/fonts/Raleway-Black.ttf
        - asset: asset/fonts/Raleway-Medium.ttf
        - asset: asset/fonts/Raleway-Regular.ttf
        - asset: asset/fonts/Raleway-Bold.ttf
        - asset: asset/fonts/Raleway-SemiBold.ttf
          style: italic

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: asset/fonts/Schyler-Regular.ttf
  #       - asset: asset/fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: asset/fonts/TrajanPro.ttf
  #       - asset: asset/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
